### ISSUE TITLE
Camel case in strings

### ISSUE THREAD

**Issue by danmarsden** [doiphode/moodle-local_course_creation_wizard#1]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

**Comment by doiphode** [comment]
Resolved in commit 6cd8a6abda2951211ee7eca1c5f1b948998f63bd
